apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: myapp
        image: ezio22/argocd-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
