name: ArgoCD Auto-Update Deployment on Image Change

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Display the content of deployment.yml
        run: |
          echo "Displaying the contents of deployment.yml:"
          cat deployments/deployment.yml

      - name: Get latest image tag from Docker Hub
        id: dockertag
        run: |
          TAG=$(curl -s "https://hub.docker.com/v2/repositories/ezio22/argocd-node-app/tags" | jq -r '.results[0].name')
          if [[ -z "$TAG" || "$TAG" == "null" ]]; then
            echo "Failed to fetch tag, or tag is null."
            exit 1
          fi
          echo "Latest tag fetched: $TAG"
          echo "::set-output name=tag::$TAG"
      
      - name: Extract current tag and update if necessary
        run: |
          CURRENT_TAG=$(grep -o 'ezio22/argocd-node-app:[^ ]*' deployments/deployment.yml | cut -d ':' -f 2)
          echo "Current tag in deployment.yml: $CURRENT_TAG"
          if [ "$CURRENT_TAG" != "${{ steps.dockertag.outputs.tag }}" ]; then
            echo "Updating deployment.yml with new tag..."
            sed -i "s|ezio22/argocd-node-app:$CURRENT_TAG|ezio22/argocd-node-app:${{ steps.dockertag.outputs.tag }}|" deployments/deployment.yml
            git config user.name 'GitHub Actions'
            git config user.email 'actions@github.com'
            git add deployments/deployment.yml
            git commit -m "Update Docker image tag to ${{ steps.dockertag.outputs.tag }}"
            git push
          else
            echo "No changes in image tag."
