name: ArgoCD Auto-Update Deployment on Image Change

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allows manual triggering.

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Display the content of deployment.yml
        run: cat deployments/deployment.yml

      - name: Extract and update the deployment file if necessary
        run: |
          CURRENT_TAG=$(grep -o 'ezio22/argocd-node-app:[^ ]*' deployments/deployment.yml | cut -d ':' -f 2)
          echo "Current tag in deployment.yml: $CURRENT_TAG"
          if [[ "$CURRENT_TAG" != "latest" ]]; then
            echo "Current tag is not 'latest'. Updating tag..."
            sed -i "s|ezio22/argocd-node-app:$CURRENT_TAG|ezio22/argocd-node-app:latest|" deployments/deployment.yml
            git config user.name 'GitHub Actions'
            git config user.email 'actions@github.com'
            git add deployments/deployment.yml
            git commit -m "Update Docker image tag to latest"
            git push
          else
            echo "Current tag is 'latest'. No update needed."
