name: Checkov Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Set for weekly
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov and handle errors
        run: checkov -d ./deployments --quiet -o json > checkov-results.json || true

      - name: Upload Checkov Results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov-results.json
