
name: Checkov Security Scan

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 mins
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d ./deployments --quiet -o txt > checkov-results.txt

      - name: Upload Checkov Results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov-results.txt
